### ISSUE TITLE
Upload your code!

### ISSUE THREAD

**Issue by phlco** [DanaMC18/shylockbot#2]
Please upload your code. Don't forget to push! What if your laptop exploded!? :scream:

**Comment by DanaMC18** [comment]
Phil! I'm trying to push my code and my terminal is saying everything is up to date... :neutral_face:

**Comment by phlco** [comment]
Can you paste in what your terminal output is? Try including it in three back ticks as a code block.

```
this is a code block
```

**Comment by DanaMC18** [comment]
```
DanaCzinsky ~/code/wdi/shylockbot on master[?]
$ git push origin master
Everything up-to-date
```

**Comment by DanaMC18** [comment]
Thank you! Silly me.

**Comment by phlco** [comment]
What does `[?]` mean.   Run `git status` and follow the commands.

Let me know if that solves it. If you solve it please report your findings here before closing the issue!
